function onCreate()
	makeLuaSprite('farm', 'backgrounds/rolnyFarm/farm', -500, -500)
	scaleObject('farm', 2.2, 2.2)
	makeLuaSprite('night', 'backgrounds/rolnyFarm/skyNight', -500, -250)
	scaleObject('night', 1, 1)
	setLuaSpriteScrollFactor('night', 0.1, 0.1)
	makeLuaSprite('black', '', -500, -500)
	makeGraphic('black', 2000, 2000, '000000')
	setProperty('black.alpha', 0.5)
	setScrollFactor('black', 0, 0)
	addLuaSprite('night', false)
	addLuaSprite('farm', false)
	addLuaSprite('black', true)
end